- README.md
- src/main/scala/Chisel/hwiotesters/OrderedDecoupledHWIOTester.scala
- src/main/scala/Chisel/hwiotesters/SteppedHWIOTester.scala
- src/test/scala/examples/Adder.scala
- src/test/scala/examples/SmallOdds4.scala
This is a first cut for expanded documentation the stepped version of the hardware tester, comments on style and comment welcome
> Readme augmentation

- src/main/scala/Chisel/hwiotesters/OrderedDecoupledHWIOTester.scala
- src/main/scala/Chisel/hwiotesters/SteppedHWIOTester.scala
and replace deprecated "!=" with "=/=".
> Convert from Int to BigInt for poke/expect values.

- build.sbt
- src/main/scala/chisel/iotesters/AdvTester.scala
- src/main/scala/chisel/iotesters/Backends.scala
- src/main/scala/chisel/iotesters/ChiselMain.scala
- src/main/scala/chisel/iotesters/ChiselSpec.scala
- src/main/scala/chisel/iotesters/Exerciser.scala
- src/main/scala/chisel/iotesters/FirrtlTerpBackend.scala
- src/main/scala/chisel/iotesters/HWIOTester.scala
- src/main/scala/chisel/iotesters/IOAccessor.scala
- src/main/scala/chisel/iotesters/OrderedDecoupledHWIOTester.scala
- src/main/scala/chisel/iotesters/PeekPokeTester.scala
- src/main/scala/chisel/iotesters/PeekPokeTesterDrivers.scala
- src/main/scala/chisel/iotesters/PeekPokeTesterUtils.scala
- src/main/scala/chisel/iotesters/SimApiInterface.scala
- src/main/scala/chisel/iotesters/SteppedHWIOTester.scala
- src/main/scala/chisel/iotesters/VerilatorBackend.scala
- src/test/scala/examples/Adder.scala
- src/test/scala/examples/DecoupledAdder.scala
- src/test/scala/examples/DynamicMemorySearch.scala
- src/test/scala/examples/GCDUnitTest.scala
- src/test/scala/examples/Hello.scala
- src/test/scala/examples/MaxN.scala
- src/test/scala/examples/RealGCD.scala
- src/test/scala/examples/Router.scala
- src/test/scala/examples/SmallOdds3.scala
- src/test/scala/examples/SmallOdds4.scala
- src/test/scala/examples/Solutions.scala
- src/test/scala/examples/VecShiftRegister.scala
This includes the usedevelopmentversions branch (changes to build.sbt).
> Lowercase chisel

- src/main/scala/chisel3/iotesters/Backends.scala
- src/main/scala/chisel3/iotesters/ChiselMain.scala
- src/main/scala/chisel3/iotesters/Driver.scala
- src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala
- src/main/scala/chisel3/iotesters/PeekPokeTester.scala
- src/main/scala/chisel3/iotesters/PeekPokeTesterUtils.scala
- src/main/scala/chisel3/iotesters/SimApiInterface.scala
- src/main/scala/chisel3/iotesters/VCSBackend.scala
- src/main/scala/chisel3/iotesters/VerilatorBackend.scala
This change removes circuit graphs with ucb-bar/chisel3#259
> No More Circuit Graph

- src/main/scala/chisel3/iotesters/AdvTester.scala
- src/main/scala/chisel3/iotesters/Backends.scala
- src/main/scala/chisel3/iotesters/ChiselMain.scala
- src/main/scala/chisel3/iotesters/Driver.scala
- src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala
- src/main/scala/chisel3/iotesters/PeekPokeTester.scala
- src/main/scala/chisel3/iotesters/SimApiInterface.scala
- src/main/scala/chisel3/iotesters/VCSBackend.scala
- src/main/scala/chisel3/iotesters/VerilatorBackend.scala
- src/main/scala/chisel3/iotesters/compatibility.scala
Refactor testers for various tester drivers to pass log & waveform files.
> Refactor testers for log & waveform files

- README.md
README now points readers to project wiki for more details
> Added PeekPokeTester information to the ReadMe

- src/main/scala/chisel3/iotesters/VCSBackend.scala
> fix clock names for vcs

- src/main/scala/chisel3/iotesters/Backends.scala
- src/main/scala/chisel3/iotesters/ChiselMain.scala
- src/main/scala/chisel3/iotesters/Driver.scala
- src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala
- src/main/scala/chisel3/iotesters/PeekPokeTester.scala
- src/main/scala/chisel3/iotesters/PeekPokeTesterUtils.scala
- src/main/scala/chisel3/iotesters/SimApiInterface.scala
- src/main/scala/chisel3/iotesters/VCSBackend.scala
- src/main/scala/chisel3/iotesters/VerilatorBackend.scala
I hope this resolve #32. Driver creates a temp dir unless we give one.
> create temp directory to prevent thread unsaftety

- src/main/scala/chisel3/iotesters/ChiselMain.scala
- src/main/scala/chisel3/iotesters/Driver.scala
- src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala
- src/main/scala/chisel3/iotesters/PeekPokeTester.scala
- src/main/scala/chisel3/iotesters/TesterOptions.scala
- src/test/scala/examples/GCDSpec.scala
Some cleanup of the way new config stuff is used
> Execution cleanup 2

- src/main/scala/chisel3/iotesters/Driver.scala
- src/test/scala/examples/GCDSpec.scala
useful for debugging, will launch the firrtl interpreter on user specified module
> make way to call repl with a chisel circuit

- src/main/scala/chisel3/iotesters/ChiselMain.scala
- src/main/scala/chisel3/iotesters/VCSBackend.scala
- src/main/scala/chisel3/iotesters/VerilatorBackend.scala
Fix API change due to ucb-bar/firrtl@be87c1e2481d14a2e0b68668fbfd901d3416dddd
> InferReadWriteAnnotation moved down into memlib.

- build.sbt
- src/main/scala/chisel3/iotesters/Exerciser.scala
- src/main/scala/chisel3/iotesters/OrderedDecoupledHWIOTester.scala
- src/main/scala/chisel3/iotesters/SteppedHWIOTester.scala
- src/test/scala/chisel3/iotesters/DriverSpec.scala
- src/test/scala/examples/Adder.scala
- src/test/scala/examples/DecoupledAdder.scala
- src/test/scala/examples/DynamicMemorySearch.scala
- src/test/scala/examples/GCDSpec.scala
- src/test/scala/examples/GCDUnitTest.scala
- src/test/scala/examples/Hello.scala
- src/test/scala/examples/MaxN.scala
- src/test/scala/examples/PeekPokeBundleSpec.scala
- src/test/scala/examples/RealGCD.scala
- src/test/scala/examples/Router.scala
- src/test/scala/examples/SmallOdds3.scala
- src/test/scala/examples/SmallOdds4.scala
- src/test/scala/examples/VecShiftRegister.scala
This should be merged when ucb-bar/chisel3#372 is merged.
> Support onetrueliteral (and new width specifier).

- src/main/scala/chisel3/iotesters/ChiselMain.scala
- src/main/scala/chisel3/iotesters/VCSBackend.scala
- src/main/scala/chisel3/iotesters/VerilatorBackend.scala
recent changes in firrtl annotation syntax broke some of the execution stuff here
> small syntactic changes for annotations

- src/test/scala/examples/GCDSpec.scala
made gcdspec example correctly modify options by copying existing options instead of creating new default ones with modifications
> Show proper method for modifying options

- src/main/scala/chisel3/iotesters/Driver.scala
Fixes  #82 so I can peek/poke verbosely...
> Fixes  #82 Passes tester options down to tester

- src/main/scala/chisel3/iotesters/ChiselPokeSpec.scala
Allow options to be specified while providing simple defaults.
I assume there's no current structure that combines both the backend and options?
> Expose options in poke testers

- src/main/scala/chisel3/iotesters/PeekPokeTester.scala
This may be temporary if we come up with a better internal chisel API. For the moment, it allows tests to pass.
> Provide replacement for demise of flatten().

- src/main/scala/chisel3/iotesters/ChiselMain.scala
- src/main/scala/chisel3/iotesters/VerilatorBackend.scala
This should resolve the issue in https://groups.google.com/forum/#!topic/chisel-users/2cfBgvQpDcc
@ucbjrl I'm not using chisel testers anymore, so I'm sure we can still compile this branch...
> fix verilator internal signal errors

- src/test/scala/examples/ALUTester.scala
- src/test/scala/examples/ConcurrentDecoupledTestingSpec.scala
- src/test/scala/examples/RerunWithoutElaboratonAndCompileSpec.scala
Provides an example of using the advance tester to handle multiple independent decoupled interfaces
> Parallel gcd example

- src/main/scala/chisel3/iotesters/Exerciser.scala
- src/main/scala/chisel3/iotesters/SteppedHWIOTester.scala
- src/test/scala/examples/AdvTesterSpec.scala
- src/test/scala/examples/ConcurrentDecoupledTestingSpec.scala
- src/test/scala/examples/DecoupledAdder.scala
- src/test/scala/examples/DynamicMemorySearch.scala
- src/test/scala/examples/GCDSpec.scala
- src/test/scala/examples/RealGCD.scala
- src/test/scala/examples/Router.scala
Reg(init -> RegInit(
log2Up -> Log2Ceil
> Fix deprecated code

- src/test/scala/examples/BundleInitSpec.scala
Relevant to question originally from Chris Celio to chisel group on  4/17/14
> Add example of one way to initialize bundles.

- src/main/scala/chisel3/iotesters/Driver.scala
- src/test/scala/chisel3/iotesters/LoggingUsageSpec.scala
- src/test/scala/examples/InterpreterVerilatorConsistencySpec.scala
Driver.execute will now automatically set logging options
Added tests for this
DO NOT MERGE UNTIL firrtl PR #488 has been merged
> Add firrtl PR 488 support for setting logging options

- src/main/scala/chisel3/iotesters/IOAccessor.scala
- src/main/scala/chisel3/iotesters/PeekPokeTesterUtils.scala
- src/main/scala/chisel3/iotesters/SteppedHWIOTester.scala
- src/main/scala/chisel3/iotesters/VCSBackend.scala
- src/test/scala/examples/AdvTesterSpec.scala
- src/test/scala/examples/BundleInitSpec.scala
- src/test/scala/examples/DecoupledAdder.scala
- src/test/scala/examples/GCDSpec.scala
- src/test/scala/examples/RealGCD.scala
Fix several classes to use ActualDirection/DataMirror.directionOf API
Fixed up Flip and UInt literal api references in several tests
> Updating to keep up with Direction mega PR

- src/test/scala/examples/DynamicMemorySearch.scala
- src/test/scala/examples/Router.scala
See https://github.com/freechipsproject/chisel3/pull/672
> Explicitly cast reset to Bool

- project/plugins.sbt
Don't be put off by the apparent list of commits. There's only one real change: to project/plugins.sbt
> Update from release

- src/main/scala/chisel3/iotesters/Driver.scala
Small fixes that came up in building a repl tutorial
> Pass repl args

- src/main/scala/chisel3/iotesters/package.scala
- src/test/scala/examples/BundleInitSpec.scala
- src/test/scala/examples/DecoupledAdder.scala
- src/test/scala/examples/InterpreterVerilatorConsistencySpec.scala
- src/test/scala/examples/Router.scala
Prepare for InvalidateAPI. Ensure all output signals are driven.
> Ensure all output signals are driven - prep for InvalidateAPI.

- src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala
Workaround for https://github.com/freechipsproject/firrtl/issues/731, relies on https://github.com/freechipsproject/firrtl/pull/747
> Use mutable loadAnnotations in FirrtlTerpBackend

- src/main/scala/chisel3/iotesters/PeekPokeTesterUtils.scala
See freechipsproject/firrtl#786
> Adapt to Cleaning up BlackBoxSourceHelper

- README.md
> Removed redundant text in doc

- src/main/scala/chisel3/iotesters/Driver.scala
- src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala
- src/main/scala/chisel3/iotesters/IVLBackend.scala
- src/main/scala/chisel3/iotesters/PeekPokeTester.scala
- src/main/scala/chisel3/iotesters/SimApiInterface.scala
- src/main/scala/chisel3/iotesters/TreadleBackend.scala
- src/main/scala/chisel3/iotesters/VCSBackend.scala
- src/main/scala/chisel3/iotesters/VerilatorBackend.scala
- src/test/scala/chisel3/iotesters/ZeroWidthIOSpec.scala
- src/test/scala/examples/MultiIOModule.scala
- src/test/scala/examples/SecondClockDrivesRegisterSpec.scala
This depends on freechipsproject/chisel3#1162
> Support migration of dontTouch, RawModule, MultiIOModule from experimental

- src/main/scala/chisel3/iotesters/PeekPokeTester.scala
Last week, I was looking for how to read the value of the current step simulation without success. [Obviously it was not documented.](https://stackoverflow.com/a/58029608/4422957)
So here is a documentation proposal for some PeekPokeTesters methods.
> PeekPokeTesters methods documentation

- src/test/scala/examples/BoreSpec.scala
Proves that tool chain to treadle works for boring utils.
> Add a test that shows boring utils works in iotesters

- src/main/scala/chisel3/iotesters/PeekPokeTester.scala
- src/main/scala/chisel3/iotesters/TreadleBackend.scala
- src/test/scala/examples/BoreSpec.scala
- src/test/scala/examples/SyncReadMemTest.scala
> 1.3.x cherrypick sync mem

- src/main/scala/chisel3/iotesters/TreadleBackend.scala
Attempt to fix chisel-tutorial problem
when memories have certain latencies that
are not being cleaned up by VerilogMemDelay pass
> VerilogMemDelays was not running for all treadle invocations

- src/main/scala/chisel3/iotesters/TreadleBackend.scala
> An earlier attempt to fix dshlw leaked into master

- .github/workflows/test.yml
- build.sbt
- build.sc
Basically taken from Treadle: https://github.com/chipsalliance/treadle/blob/master/.github/workflows/test.yml
> Add auto-publish workflow

- project/plugins.sbt
missed adding this. should publish on push to master
> Need sbt-ci-release to publish on PR merge
