freechipsproject/chisel-testers

src/test/scala/examples/DynamicMemorySearch.scala
src/test/scala/examples/Router.scala

The upper bound in the loop in src/test/scala/examples/Router.scala is benign since we use modulus, but the name is number_of_packets_to_send so while we're here ...

Replace 'to' with 'until' in for loops.

---

src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala
src/test/scala/examples/GCDSpec.scala
src/test/scala/examples/Router.scala

firrtl intermediate files now have correct suffix ".fir"
Add a version of GCDSpec that uses PeekPokeTester

Change firrtl file suffix to be ".ir"

---

src/main/scala/chisel3/iotesters/AdvTester.scala

This lets AdvTester print stack traces when it encounters exceptions like #38.

Better exception handling in AdvTester

---

src/main/scala/chisel3/iotesters/VCSBackend.scala

Makes VPD dumps are flushed every cycle. This is important for debugging when we encounter any exceptions in tester, but can be much slower.

flush vpd every cycle for debugging

---

src/main/scala/chisel3/iotesters/ChiselMain.scala
src/main/scala/chisel3/iotesters/VCSBackend.scala
src/main/scala/chisel3/iotesters/VerilatorBackend.scala

Signal names start with its top module name, not with 'v'

change signal name for verilator 3.886

---

src/main/scala/chisel3/iotesters/AdvTester.scala
src/main/scala/chisel3/iotesters/PeekPokeTester.scala

Should we remove `verbose` as an argument to the PeekPokeTester constructor? Related to #54

Use TesterOptions verbose instead of the argument.

---

src/main/scala/chisel3/iotesters/ChiselMain.scala
src/main/scala/chisel3/iotesters/VCSBackend.scala
src/main/scala/chisel3/iotesters/VerilatorBackend.scala

Did kind of a manual conversion, I think some code duplication could be removed by moving the invocation of Firrtl to some utility function. 
Also, why does every invocation of Firrtl use InferReadWrite?

Adhere to new Firrtl Compiler API

---

src/main/scala/chisel3/iotesters/Driver.scala
src/main/scala/chisel3/iotesters/PeekPokeTesterUtils.scala

One resulted in one of the Driver's execute methods always returning
true (PASS).
One was just a typo on a printed message.

Fix some typos.

---

src/main/scala/chisel3/iotesters/Driver.scala
src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala
src/main/scala/chisel3/iotesters/PeekPokeTester.scala

Add comments on Driver.execute methods
Made Driver.apply use underlying execute methods and provide a couple more useful
options it can set: verbose and testerSeed.  It should be default way of invoking tests
unless need for more backend toolchain option control pushes user towards execute methods
Add step number to expect messages
Fixed number of successful expects not be counted in interpreter based tester
Failed expects print even if verbose is off
Fixed type shadowing on PeekPokeTester peekAt

Fixed problem with lack of reporting of failed tests

---

src/main/scala/chisel3/iotesters/Driver.scala
src/test/scala/examples/GCDSpec.scala

to be test_run_dir/<sanitized-spe…c-classname><hashcode>
It's just to hard to pick up dut class name without double elaborating, so this should be a decent compromise. Adding hashcode makes separate directories for multiple tests within the same spec file which seems better

change default directory for tester 

---

src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala
src/main/scala/chisel3/iotesters/PeekPokeTester.scala
src/main/scala/chisel3/iotesters/VerilatorBackend.scala

Problem was implicit conversion of negative ints to positive BigInt representation.
Removed the implicits after discussion with @donggyukim 
This is a simpler more elegant fix that in PR #63 
Seems to works with dsptool tests that exposed this bug originally

Fix poke expect neg ints

---

.gitignore

It's helpful for me if git ignores /lib added by dsp-framework and/or craft2-chip

Ignore lib (for rocket build)

---

src/main/scala/chisel3/iotesters/PeekPokeTester.scala
src/test/scala/examples/BigNumbers.scala

Fixed by making long specific poke functions
Added test for behavior reported in Chisel3 Issue #425

Poking large longs was converting longs to int and losing large values.

---

src/test/scala/chisel3/iotesters/AggregateOrderingSpec.scala
src/test/scala/chisel3/iotesters/VectorPeekPokeSpec.scala

Added at test AggregateOrderingSpec that shows some of the quirks involved.
Nothing changed in API, though the stuff presents some reasons to do so

Disambiguating the poking and peeking of aggregates

---

src/main/scala/chisel3/iotesters/VerilatorBackend.scala
src/test/scala/examples/Adder.scala

This seems like an obvious fix, but it does change the API.  Although currently the API behavior is different between the interpreter and verilator backend
Change PeekPokeTester #peek and #expect to return signed BigInt if the signalId they are given is an SInt
Add a signed adder test to confirm this works
This needs to be further built out with fixed point

API change: Change  peek and expect to get negatives when applied to SInt

---

src/main/scala/chisel3/iotesters/IOAccessor.scala
src/main/scala/chisel3/iotesters/VerilatorBackend.scala
src/test/scala/examples/Adder.scala

This adds support for `Record` as a super-class of `Bundle` for `Module.io`
NOTE - This includes #89 in order to facilitate testing.

Prog bundle - fix #88

---

src/main/scala/chisel3/iotesters/VerilatorBackend.scala

Basically, after previous changes, Peek would return the correct (signed) BigInt, but, in verbose mode, it would print the unsigned version of the returned value. Theoretically, that's ok too, but it's inconsistent with what Poke (and otherwise Peek.litValue) would give you... This only addresses peek on InstanceId (and not on peek Path:String -- since you lose sign info there). This fix was only applied to VerilatorBackend. It'd probably make sense to double check consistency for Interpretter/VCS backend, but that's not something I'm concerned with atm. @chick can you stare at this and merge if you're OK? This should actually be a quick fix ;)

make peek print bigint with correct sign

---

src/main/scala/chisel3/iotesters/ChiselPokeSpec.scala
src/test/scala/chisel3/iotesters/ChiselPokeSpec.scala

Implementation for #73.
See the included test code for an API example.
Feedback is welcome on the more experimental ChiselImplicitPokeSpec. Especially if there is a way to properly overload triple-equals on FlatSpec.

More ScalaTest-y specs

---

src/main/scala/chisel3/iotesters/PeekPokeTesterUtils.scala
src/main/scala/chisel3/iotesters/VCSBackend.scala
src/main/scala/chisel3/iotesters/VerilatorBackend.scala
src/test/resources/AddTwoAddThree.v
src/test/scala/chisel3/iotesters/BlackBoxVerilogDeliverySpec.scala

Fixes a problem where the Driver execution harness was not passing down annotations from higher level libraries.  Add hooks to call verilator and vcs in a way to know about verilog files placed in the target directory

Pass through annos, support for black box verilog implementations

---

src/main/scala/chisel3/iotesters/VCSBackend.scala
src/main/scala/chisel3/iotesters/VerilatorBackend.scala

@chick basically, the symptom was: the BigInt out of Verilator wasn't always normalized to width.
I.e.  5 bit wide -8 would actually be output as 248. So if you did the normalization assuming 1 << 5 = 32, you'd get 216 instead of -8... Basically needed to adjust the perceived width as the max of the BigInt (unsigned) width or the Chisel width. 
Should be super quick review. Plz merge ASAP

fixed sign out of verilator for when bitLength isn't as expected

---

src/main/scala/chisel3/iotesters/TesterOptions.scala
src/main/scala/chisel3/iotesters/VCSBackend.scala
src/main/scala/chisel3/iotesters/VerilatorBackend.scala
src/test/scala/chisel3/iotesters/DriverSpec.scala

fix --test-command so that it is used in verilator and vcs backends
add test to DriverSpec to illustrate it's use.
added two other tests to DriverSpec to illustrate overriding directories

--test-command was broken

---

src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala
src/main/scala/chisel3/iotesters/VerilatorBackend.scala

Existing expect error looked like
"port" -> 99 == 106
Change this to be 
"port" got 99 expected 106
Makes it much clearer what those values are

Change expect error message 

---

src/main/scala/chisel3/iotesters/ChiselMain.scala
src/main/scala/chisel3/iotesters/VerilatorBackend.scala

and use the already computed cppHarnessFile instead of only the name (and not the path) component.

Fix argument list for verilogToCpp().

---

src/main/scala/chisel3/iotesters/VCSBackend.scala
src/main/scala/chisel3/iotesters/VerilatorBackend.scala

This might have been intentionally left out, but I think this was originally a bug. 
I wanted to test the generated Verilog (via my custom transform) against a testbench working with Verilator, but b/c the transform wasn't being run, I was always artificially getting the right result. The benefit of using Verilator + VCS is -- you should, assuming that you're providing all the right Verilog, etc. files, be able to test with the post-transform result. 
In general, I'm not sure why the decision was made to run Firrtl outside of chisel3.Driver.execute -- If it was simply to get the BlackBox resource directory in, I assume missing the transforms list was just a mistake. Though, if that's the case, there's got to be a less error-prone way to write this. 
I also removed the transform/annotation …

fixed bug - verilator + vcs backends weren't propagating transforms correctly 

---

src/test/scala/examples/RerunWithoutElaboratonAndCompileSpec.scala

Shows how to re-run a test without re-running the verilator compiler.
This also illustrates that this method does re-elaborate the circuit under tests.
Issue #118 would like this second time sink eliminated.

Example of how to re-run a test without re-running verilator

---

src/main/scala/chisel3/iotesters/ChiselMain.scala
src/main/scala/chisel3/iotesters/PeekPokeTesterUtils.scala
src/main/scala/chisel3/iotesters/VerilatorBackend.scala
src/test/scala/chisel3/iotesters/VecFillSpec.scala
src/test/scala/verilator/doohickey.scala

Recent changes to emitter stuff in firrtl, broke the rather brittle verilator backend.  I have cleaned this up a fair amount, although there is probably still some room for improvement.
Reworked the VerilatorCppHarnessCompiler stuff.
It seemed to be unnecessarily using Transforms to do a simple template substitution.
chiselMain had it's own hooks into the above.  Cleaned this up as much as I dared
Fix deprecated code
Reg(init -> RegInit(
log2Up -> Log2Ceil
Fixed up style (I needed this to debug this mess)

Fix compiler errors due to firrtl emitter api changes

---

src/main/scala/chisel3/iotesters/VCSBackend.scala
src/main/scala/chisel3/iotesters/VerilatorBackend.scala
src/test/scala/chisel3/iotesters/VecFillSpec.scala

Custom transforms specified by annotations were not being run by Driver.execute when using the verilator backend

Fix verilator custom transforms not being run

---

src/test/scala/examples/Router.scala

When the VecLike trait was removed from Mems, the indicies field disappeared.

Remove references to obsolete Mem fields.

---

.gitignore
src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala
src/test/scala/chisel3/iotesters/DriverSpec.scala
src/test/scala/examples/test_worksheet.sc

setUpFirrtlBackend was failing to use the previously emitted firrtl code
Some small style cleanups
Fixes [FirrtlInterpreter Issue #86](/ucb-bar/firrtl-interpreter/issues/86)

Fix double elaboration of DUT when using the interpreter

---

build.sbt
project/build.properties
project/plugins.sbt
src/main/scala/chisel3/iotesters/ChiselSpec.scala

bump versions; replace PropertyCheckConfig with PropertyCheckConfiguration.
This also address issue #143.

Prepare for Scala 2.12

---

src/main/scala/chisel3/iotesters/ChiselPokeSpec.scala

Small one-liner fix to ChiselPokeSpec.scala.  Fix PokeTester trait.

pass testerBackend argument, not hardcoded firrtl backend to PokeTester trait

---

src/main/scala/chisel3/iotesters/VerilatorBackend.scala
src/test/scala/verilator/Verilator.scala
src/test/scala/verilator/ZeroWidth.scala

I had some IOs with 0-width wires that were causing issues with chisel-testers.
Should I add a test too?

Don't add 0-width wires to verilated c++

---

build.sbt
project/build.properties
project/plugins.sbt

To clean, test, and build Scala 2.11 and Scala 2.12 versions:
% sbt +clean +test +publishLocal
NOTE: You need to be running Java 8 to build the 2.12 version.

Update sbt to 0.13.16; add Scala 2.12 support.

---

src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala
src/test/scala/chisel3/iotesters/MemPokeSpec.scala

Add support for peek and poking memories to the interpreter backend.
Add a test to show that it works
This is an interpreter only fix for [/chisel-testers/issues/166](https://github.com/freechipsproject/chisel-testers/issues/166)

Add support for peek and poking memories to the interpreter backend.

---

src/main/scala/chisel3/iotesters/Driver.scala

Fix so that now arguments are passed down to the repl.

executeFirrtlRepl did not pass along args

---

src/main/scala/chisel3/iotesters/VerilatorBackend.scala
src/test/scala/examples/GCDSpec.scala

Changed replace to replaceFirst to only change the dutname
in constructing verilator io interface
Changed GCDSpec port names to trigger the bug and verify fix.

Running verilator broken if port name contains dutname as substring

---

src/main/scala/chisel3/iotesters/Exerciser.scala
src/main/scala/chisel3/iotesters/SteppedHWIOTester.scala
src/test/scala/verilator/doohickey.scala

firrtl freechipsproject/firrtl#706 changes the way submodule connections are handled, and causes hardware testers to provoke unconnected errors. This pr adds `DontCare`'s to avoid the problem.
This may not be the correct long-term solution.

Invalidateapifix

---

src/test/scala/chisel3/iotesters/MemPokeSpec.scala

Now that Bundle is an abstract class (freechipsproject/chisel3#774), replace
a bare Bundle with a concrete one.

Fix use of bare Bundle in MemPokeSpec.

---

src/main/scala/chisel3/iotesters/ChiselMain.scala
src/main/scala/chisel3/iotesters/VCSBackend.scala
src/main/scala/chisel3/iotesters/VerilatorBackend.scala

Fix for freechipsproject/firrtl#721 and freechipsproject/chisel3#767.

Update in light of annotations refactor.

---

src/main/scala/chisel3/iotesters/Driver.scala
src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala
src/main/scala/chisel3/iotesters/PeekPokeTester.scala
src/main/scala/chisel3/iotesters/PeekPokeTesterUtils.scala
src/main/scala/chisel3/iotesters/SimApiInterface.scala
src/main/scala/chisel3/iotesters/VCSBackend.scala
src/main/scala/chisel3/iotesters/VerilatorBackend.scala
src/test/scala/examples/MultiIOModule.scala

Closes #174. Supersedes #176.
`ImplicitModule` has `clock` and `reset`, which chisel testers currently assume exist.

Use ImplicitModule instead of LegacyModule.

---

src/main/scala/chisel3/iotesters/VCSBackend.scala

Strip dut name prefix from signal names for VCS
Remove unused imports.

Set symbol separator for VCS harness - fix #193

---

src/main/scala/chisel3/iotesters/VerilatorBackend.scala

Cleanup several style violations in same file.

Cleanup deprecated loadAnnotations call.

---

src/main/resources/vpi.h
src/main/resources/vpi_register.cpp
src/main/scala/chisel3/iotesters/ChiselMain.scala
src/main/scala/chisel3/iotesters/ChiselPokeSpec.scala
src/main/scala/chisel3/iotesters/CommandEditor.scala
src/main/scala/chisel3/iotesters/Driver.scala
src/main/scala/chisel3/iotesters/IVLBackend.scala
src/main/scala/chisel3/iotesters/PeekPokeTesterUtils.scala
src/main/scala/chisel3/iotesters/TesterOptions.scala

Add Icarus Verilog, a free open source verilog simulator as backend
- Iverilog is really usefully when you want to simulate you design which includes one or more blackbox.
And only verilog model is available for the blackbox.
- It save your VCS licences at the same time.
- Iverilog is much slower the VCS and verilator, especially for large design. But it is fast enough for small module level verification
Need to install iverilog, and setting $IVL_HOME, usually
```bash
export IVL_HOME=/usr/include/iverilog
```
or
```bash
export IVL_HOME=/usr/local/include/iverilog
```

Add iverilog as a backend

---

src/test/scala/chisel3/iotesters/BlackBoxVerilogDeliverySpec.scala

Add the assumption that VCS is available.
Remove the expected AssertionError - I'm unsure why we would expect the VCS implementation to fail.

Enable VCS blackbox test.

---

build.sbt
build.sc
src/main/scala/chisel3/iotesters/Driver.scala
src/main/scala/chisel3/iotesters/TesterOptions.scala
src/main/scala/chisel3/iotesters/TreadleBackend.scala
src/test/scala/chisel3/iotesters/MemPokeSpec.scala
src/test/scala/examples/AccumBlackBoxSpec.scala

- Create a treadle backend and setup modeled on interpreter
- Make treadle default backend, although most tests explicitly declare a backend
- Add treadle to legal backends list
- Fix up MemoryPoke tests (was getting messed up by DCE)
- Fix up black box tests, treadle has separate black box API now
- Add treadle to sbt dependencies
- Add treadle to mill dependencies

Add treadle support.

---

src/main/scala/chisel3/iotesters/VerilatorBackend.scala

I believe this solves the mystery of why some versions of verilator appear to fail with a:
```bash
Undefined symbols for architecture x86_64:
"vl_finish(char const*, int, char const*)", referenced from:
VL_FINISH_MT(char const*, int, char const*) in verilated.o
ld: symbol(s) not found for architecture x86_64
```
The harness generated by `chisel3/src/main/resources/chisel3/top.cpp` contains a definition of `vl_finish()` while the harness generated by `chisel-testers/src/main/scala/chisel3/iotesters/VerilatorBackend.scala` doesn't.
Tests run with pure Chisel3 and FIRRTL will pass without problems, while tests using chisel-testers will fail at the link stage.
This PR converts multiple `codeBuffer.append()`s with individual C++ source lines into two `codeBuffer.append()`s with triple quotes …

Cleanup harness generation and add missing vl_finish().

---

src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala
src/main/scala/chisel3/iotesters/TesterOptions.scala
src/main/scala/chisel3/iotesters/TreadleBackend.scala
src/main/scala/chisel3/iotesters/VerilatorBackend.scala
src/test/scala/examples/GCDSpec.scala

- Add new flag suppressVerilatorVCD to TesterOptions
- setUpVerilatorBackend looks at this flag and uses it
- added tests to show that this works
- This combined with [firrtl pr 794](https://github.com/freechipsproject/firrtl/pull/794/files) resolves [chisel issue 808](https://github.com/freechipsproject/chisel3/issues/808)

Add flag to stop verilator simulation from writing a VCD

---

src/main/scala/chisel3/iotesters/PeekPokeTesterUtils.scala
src/main/scala/chisel3/iotesters/VerilatorBackend.scala
src/test/scala/chisel3/iotesters/ToolChainSpec.scala

We'd like to be able to use the current **vcs** command line options edit facility with **verilator**.
This replaces the direct call to `BackendCompilationUtilities.verilogToCpp()` with a local (chisel-testers) implementation which essentially duplicates the **vcs** facility.
Questions to be resolved:
- is this appropriate, or should we move this facility from **chisel-testers** to **firrtl**?
- the preliminary implementation tries to use existing **vcs** options instead of defining new **verilator** equivalents. Should we introduce distinct **verilator** options?

Add support for vcs command line options to verilator.

---

src/main/scala/chisel3/iotesters/AdvTester.scala
src/main/scala/chisel3/iotesters/ChiselPokeSpec.scala
src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala
src/main/scala/chisel3/iotesters/PeekPokeTester.scala
src/main/scala/chisel3/iotesters/Pokeable.scala
src/main/scala/chisel3/iotesters/TreadleBackend.scala
src/test/scala/chisel3/iotesters/EnumSpec.scala
src/test/scala/examples/AdvTesterSpec.scala
src/test/scala/examples/PeekPokeBundleSpec.scala

This PR adds enum support to `PeekPokeTesters` and `AdvTesters` by creating a new `Pokeable` typeclass which we use instead of `Bits`.
*Related issue:* freechipsproject/chisel3#932

Add enum support

---

src/main/scala/chisel3/iotesters/TreadleBackend.scala
src/test/scala/examples/ComplexMemoryLoadingSpec.scala

- Fixed by passing down annotations processed by firrtl (they were being dropped)
- Expanded ComplexMemoryLoadingSpec with treadle test
Thanks to @nhynes for finding the bug.

Treadle was not working with composite memories

---

src/test/scala/examples/RerunWithoutElaboratonAndCompileSpec.scala

- I believe this test was re-activated in broken form
- Happened when fixed the verilator check method
- Made this into a single test to ensure sequential execution
- Moved the working directory for test into test_run_dir

Fix RerunWithoutElaboration

---

src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala
src/main/scala/chisel3/iotesters/TreadleBackend.scala

@ucbjrl: Here's one solution to the problem you identified here: https://github.com/freechipsproject/firrtl/pull/1005#issuecomment-487235820.
The underlying problem is that for target directories which are not `"."` this winds up generating two copies of the same `TargetDirAnnotation`. One by `Driver.getAnnotations` inside testers and another when `CommonOptions.toAnnotations` is used to convert `CommonOptions` to annotations before being passed to `FirrtlStage` in `firrtl.Driver`. This was not a problem before because `commonOptions.targetDirName` was the only thing checked inside of `firrtl.Driver` with the exception of any downstream transforms which may have relied on `TargetDirAnnotation`.
This likely motivates a more rapid push to migrate Stage/Phase into the Big6. Similar bugs may …

Filter TargetDirAnnotations between Driver.execute

---

src/main/scala/chisel3/iotesters/Driver.scala
src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala
src/main/scala/chisel3/iotesters/TreadleBackend.scala

`logger.LogLevelAnnotation` and `firrtl.stage.FirrtlCircuitAnnotation`
(without this, chisel-tutorial fails to run tests successfully)

Centralize (for testers) annotation filtering and filter out some more -

---

src/main/scala/chisel3/iotesters/SimApiInterface.scala
src/test/scala/chisel3/iotesters/ZeroWidthIOSpec.scala

DO NOT MERGE UNTIL PR #238 HAS BEEN MERGED
THIS SUPERSEDES PR #237 
- verilog 0.W input has been removed
- this fix removes them from the IO maps used to used to communicate with simulation
- provides a test that failed prior to the fix

Fix problem with circuits with zero width input using verilator

---

src/main/scala/chisel3/iotesters/TreadleBackend.scala

Provide the optional CircuitForm argument to the TreadleTester constructor to indicate it shouldn't run the chirrtl to FIRRTL transforms since we're already in low FIRRTL.

Quick fix (hack) for Stage/Phase CircuitForm issues.

---

src/main/scala/chisel3/iotesters/VerilatorBackend.scala
src/test/scala/examples/GCDSpec.scala
src/test/scala/examples/SecondClockDrivesRegisterSpec.scala

of dut->_eval_settle(dut->__VlSymsp)
Test in SecondClockDrivesRegisterSpec will only work with this change.
GCDSpec has code to do regression work to make sure
the above change did not significantly slow the verilator simulation.

Change the verilator generation code to call dut->eval() instead

---

src/main/scala/chisel3/iotesters/ChiselMain.scala

This fixes a bug when trying to build unidoc of chisel3 and
chisel-testers for the website. I'm not 100% sure of the interaction,
but additional plugins/libraries may use the package "io" and cause an
error when building here.
E.g., this avoids nonsense like the following:
```
[error] /home/se/repos/github.com/freechipsproject/www.chisel-lang.org/chisel-testers/src/main/scala/chisel3/iotesters/ChiselMain.scala:159:21: object Source is not a member of package io
[error]         val ir = io.Source.fromFile(file).getLines mkString "\n"
[error]                     ^
```

Be explicit about scala.io

---

build.sc

mill Evaluator has changed, dropping its type parameter.
ScalaTest and ScalaCheck are required for the main build, not just for testing.

Fix mill issues - Evaluator arguments, scala{check,test} dependencies.

---

src/main/scala/chisel3/iotesters/PeekPokeTester.scala
src/main/scala/chisel3/iotesters/TreadleBackend.scala
src/test/scala/examples/SyncReadMemTest.scala

- Prior to this, it could be done with Mem but not SyncReadMemTest
- Changed peekAt and pokeAt to use MemBase as the type
- Added peek and poke in TreadleBackend to use MemBase

This allows the PeekPokeTester to us peekAt and pokeAt with SyncReadMem

---

src/main/resources/sim_api.h
src/main/resources/utils.fdo
src/main/resources/vpi.cpp
src/main/resources/vpi.h
src/main/scala/chisel3/iotesters/ChiselMain.scala
src/main/scala/chisel3/iotesters/ChiselPokeSpec.scala
src/main/scala/chisel3/iotesters/Driver.scala
src/main/scala/chisel3/iotesters/PeekPokeTesterUtils.scala
src/main/scala/chisel3/iotesters/TesterOptions.scala
src/main/scala/chisel3/iotesters/VSIMBackend.scala

Enable the use of Modelsim/Questasim as backend with chisel-tester
I am not really proud of adding suport for another commercial simulator but it is an important milestone for us to push forward the integration of chisel within our existing code base.
We indeed rely on lots of existing systemverilog libraries that are not supported with verilator.
I hope it will help other people as well.
I have started to test this new backend on my side but I have no idea how to integrate proper tests due to the very nature of vsim as closed-source commercial simulator.
Maybe use the same syntax as for vcs ?
`assume(firrtl.FileUtils.isVCSAvailable)`
I cannot say that it doesn't break vcs backend either as I cannot test it but other tests are still passing.
I think some of the changes of the vpi code …

Add VSIM backend (Modelsim, Questasim)

---

src/main/scala/chisel3/iotesters/PeekPokeTester.scala
src/test/scala/examples/FixedPointSpec.scala

large fixed point numbers require BigDecimal type to handle them with out precision loss
Creates  new methods:
pokeFixedPointBig
peekFixedPointBig
expectFixedPointBig
that use BigDecimal instead of Double
Fixes up a test broken for large widths

Allows working with FixedPoint IOs that are larger than 64 bits

---

src/main/scala/chisel3/iotesters/PeekPokeTester.scala
src/main/scala/chisel3/iotesters/VerilatorBackend.scala
src/test/scala/examples/FixedIsWholeTester.scala
src/test/scala/examples/IntervalSpec.scala

This fixes a problem with not providing handle for peeking intervals
And fixes a bug with extra high bits poked to simulator when using
negative numbers with fixedpoint and intervals to the verilator backend

Interval fixedpoint fixes

---

src/main/scala/chisel3/iotesters/TreadleBackend.scala

Simultaneous tests were failing without this.

TreadleTester needs to have new. 

---

src/main/scala/chisel3/iotesters/Driver.scala
src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala
src/main/scala/chisel3/iotesters/VerilatorBackend.scala

Add ability to pass an override to firrtl source down to the firrtl interpreter and to Verilator.
This functionality was used as part of the FFT Craft project but was never PR'd. The FFT
is being redone and this functionality is needed for testing and compatibility with earlier work
This is should probably be done in a better way using stage phase, so consider that a todo

Features to enable FFT development

---

src/main/scala/chisel3/iotesters/TreadleBackend.scala
src/test/scala/chisel3/iotesters/IntervalDshlTest.scala

Happened when left shifting intervals and using Treadle
This changes the compiler used by
ChiselStage in TreadleBackend
Thanks @seldridge

Fixes Dshlw error in CheckTypes

---

src/main/scala/chisel3/iotesters/TreadleBackend.scala

This fixes problem with IntervalDshlTest
Required for 3.4.0-RC3

Treadle backend now overrides firrtl options compiler

---

build.sbt
build.sc

Change build.sbt and build.sc to consider next major to be 2.5 instead
of 1.6. This brings it inline with all other main repos being x.5
After this PR is merged dsptools will need to be updated

Next major will be 2.5

---

src/main/scala/chisel3/iotesters/Driver.scala
src/main/scala/chisel3/iotesters/TesterOptions.scala
src/main/scala/chisel3/iotesters/TreadleCompatibility.scala

Treadle's Driver/TreadleOptions code has been deleted
This provides a backward compatibilty shim that provides lost treadle functionality
that constructs equivalent annotations.

Adds compatibility code to deal with Treadle no longer having a Driver

---

src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala

FirrtlInterpreter backend was eating this message
This will fix that. 
Addresses [Chisel3 Issue #1889](https://github.com/chipsalliance/chisel3/issues/1889)

Show message returned in ChiselExecutionFailure

---

build.sbt
build.sc
src/main/scala/chisel3/iotesters/FirrtlTerpBackend.scala
src/main/scala/chisel3/iotesters/IVLBackend.scala
src/main/scala/chisel3/iotesters/OrderedDecoupledHWIOTester.scala
src/main/scala/chisel3/iotesters/PeekPokeTester.scala
src/main/scala/chisel3/iotesters/SteppedHWIOTester.scala
src/main/scala/chisel3/iotesters/VCSBackend.scala
src/main/scala/chisel3/iotesters/VSIMBackend.scala
src/main/scala/chisel3/iotesters/VerilatorBackend.scala
src/test/scala/examples/FixedIsWholeTester.scala
src/test/scala/examples/FixedPointSpec.scala
src/test/scala/examples/IntervalSpec.scala

Add support for 2.13, drop relics from 2.11
- Updated build.sbt
- Removed `-Xsource:2.11` stuff
- Update scalaVersion and CrossScalaVersions
- Mostly add a bunch of `toSeq`s where needed
- Created some intermediate `ListMap`s where needed

Add support for 2.13

---

src/main/scala/chisel3/ChiselExecutionOptions.scala
src/main/scala/chisel3/Driver.scala
src/main/scala/chisel3/iotesters/Driver.scala
src/main/scala/chisel3/iotesters/PeekPokeTesterUtils.scala
src/main/scala/chisel3/stage/package.scala
src/main/scala/firrtl/Driver.scala
src/main/scala/firrtl/ExecutionOptionsManager.scala
src/main/scala/firrtl/stage/package.scala
src/main/scala/firrtl/stage/phases/DriverCompatibility.scala
src/main/scala/logger/Logger.scala
src/test/scala/chisel3/iotesters/BlackBoxVerilogDeliverySpec.scala

Many APIs that have been deprecated in firrtl and chisel3 for a long
time are removed in anticipation of the X.5 release. This project is now
on life support--users should switch to using chiseltest (aka
chisel-testers2).
There is a limited compatibility layer for iotesters.PeekPokeTesters,
see https://github.com/ucb-bar/chisel-testers2/pull/348.
These are only the changes required to get this passing with master of chisel3 and firrtl. I intend to follow this PR with a PR deprecating as many APIs in this repo as possible and pointing to chiseltest. It would be helpful to have at least _some_ doc on updating code.

Polyfill formerly deprecated now removed APIs
